import { classifyScores, normalizeInputs } from "./classify.js";
import { buildTinyInferWasm } from "../wasm/tinyInferBytes.js";

async function instantiateFromBytes(bytes) {
  const result = await WebAssembly.instantiate(bytes);
  return result.instance;
}

export async function loadTinyModel({ wasmUrl = "./public/tiny-infer.wasm" } = {}) {
  try {
    const response = await fetch(wasmUrl);
    if (!response.ok) {
      throw new Error(`WASM fetch failed with ${response.status}`);
    }
    const bytes = await response.arrayBuffer();
    const instance = await instantiateFromBytes(bytes);
    return { instance, source: wasmUrl };
  } catch (error) {
    const instance = await instantiateFromBytes(buildTinyInferWasm());
    return {
      instance,
      source: "generated bytes fallback",
      warning: error instanceof Error ? error.message : String(error),
    };
  }
}

export function runTinyModel(model, rawInputs) {
  const inputs = normalizeInputs(rawInputs);
  const started = performance.now();
  const scores = {
    calm: model.score_calm(inputs.energy, inputs.focus, inputs.noise),
    build: model.score_build(inputs.energy, inputs.focus, inputs.noise),
    explore: model.score_explore(inputs.energy, inputs.focus, inputs.noise),
  };
  const runtimeMs = performance.now() - started;

  return {
    inputs,
    scores,
    runtimeMs,
    result: classifyScores(scores),
  };
}
